{
 "title": "Mortgage Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU Activity per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prometheus\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Request Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"mortgage-app\", uri!=\"/actuator/prometheus\"}",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by(exception) (http_server_requests_seconds_max{job=\"mortgage-app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus HTTP Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count by(__name__) (prometheus_http_requests_total{job=\"prometheus\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}